services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: ["npm", "run", "dev"]
    depends_on:
      - node-server

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./node-server:/app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  gimmit:
    build:
      context: ./gimmit
      dockerfile: Dockerfile
    depends_on:
      - node-server
    volumes:
      - ./gimmit:/app
volumes:
  db_data:
